config/routes.rb
  Rails.application.routes.draw do

  get 'welcome_page/welcome_page'

  root 'welcome_page#welcome_page'

    resources :aform

end

app/models/aform.rb
class Aform < ActiveRecord::Base
end

app/controllers/aform_controller.rb
class AformController < ApplicationController
	def new
	end

	def create

		@somestuff = Aform.new(params.require(:aform).permit(:))

		@somestuff.save
		redirect_to @somestuff
	end	


	# private
 #    	def theparams
 #    	params.require(:aform).permit(:text)
 #  	end

end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_page_controller.rb
class WelcomePageController < ApplicationController
  def welcome_page
  end
end

app/helpers/aform_helper.rb
module AformHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_page_helper.rb
module WelcomePageHelper
end

app/views/aform/new.html.erb
<%= form_for :aform, url: aform_index_path do |f| %>
 
  <p>
    <%= f.label :othername %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>

 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome_page/welcome_page.html.erb
<h1>WelcomePage#welcome_page</h1>
<p>Find me in app/views/welcome_page/welcome_page.html.erb</p>